# USING API IN PROD #
FROM openjdk:17-jdk-alpine
COPY "./target/playfutday-0.0.1-SNAPSHOT.jar" "app.jar"
ENTRYPOINT ["java", "-jar", "/app.jar"]

########################################################################################################################
# USING API REST WITH H2 DATABASE
# FROM openjdk:17-jdk-alpine
# COPY "./target/playfutday-0.0.1-SNAPSHOT.jar" "app.jar"
# EXPOSE 8080
# ENTRYPOINT ["java","-jar","/app.jar"]