name: playfutday_flutter
description: Project Flutter for the screen like a red social of a people that likes football.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-109.0.dev <4.0.0"

dependencies:
  flutter_form_bloc: ^0.30.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.0
  http: ^0.13.5
  get_it: ^7.2.0
  injectable: ^2.1.0
  http_interceptor: ^1.0.1
  shared_preferences: ^2.0.17
  cupertino_icons: ^1.0.2
  get:
    ^4.6.1
  image_picker: ^0.8.6+1
  image_cropper: ^3.0.1
  flutter:
    sdk: flutter
  bloc_concurrency: ^0.2.1
  stream_transform: ^2.1.0
  file_picker: ^5.2.6
  card_swiper: ^2.0.4
  curved_navigation_bar: ^1.0.3
  animate_do: ^2.0.0
  flutter_cupertino_datetime_picker: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.2.19
  loading_animation_widget: ^1.2.0+4  
  pin_code_fields: ^7.4.0
  form_builder_file_picker: ^3.0.0
  google_fonts: ^4.0.4
  animations: ^2.0.7
  readmore: ^2.2.0
  flutter_scroll_to_top: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png


flutter:
  uses-material-design: true
  assets:
    - assets/images/